import canonicalLaneMathlib.AdmissibleClass
import HautevilleHouse.DevelopmentalBiologyMorphogenGradientsTheoremCanonicalLaneLean.MorphogenProduction
import HautevilleHouse.DevelopmentalBiologyMorphogenGradientsTheoremCanonicalLaneLean.DiffusionTransport
import HautevilleHouse.DevelopmentalBiologyMorphogenGradientsTheoremCanonicalLaneLean.GradientFormation
import HautevilleHouse.DevelopmentalBiologyMorphogenGradientsTheoremCanonicalLaneLean.SignalTransduction
import HautevilleHouse.DevelopmentalBiologyMorphogenGradientsTheoremCanonicalLaneLean.PositionalInformation

namespace HautevilleHouse
namespace DevelopmentalBiologyMorphogenGradientsTheoremCanonicalLaneLean

structure CellAdmissibleClass where
  object : DevelopmentalBiologyAdmittedObject
  morphogenProduction : MorphogenProductionPackage CellAdmissibleClass
  diffusionTransport : DiffusionTransportPackage CellAdmissibleClass
  gradientFormation : GradientFormationPackage CellAdmissibleClass
  signalTransduction : SignalTransductionPackage CellAdmissibleClass
  positionalInformation : PositionalInformationPackage CellAdmissibleClass

end DevelopmentalBiologyMorphogenGradientsTheoremCanonicalLaneLean
end HautevilleHouse